# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html

manifest:
  
  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro

  defaults:
    remote: nxpmicro

  projects:
    - name: mcux-sdk-examples
      revision: aec2981c3ee12bdaad74aec870ceff3d213e775f
      path: examples

  self:
    path: core
