# The west manifest file (west.yml) for MCUXpresso SDK overall delivery.
#
# The per-workspace west configuration file, ${workspace_path}/.west/config,
# specifies the path of the project containing this manifest file, the
# path is relative to the workspace location ${workspace_path}.
#
#     [manifest]
#     path = core
#
# See the west documentation for more information:
#
# https://docs.zephyrproject.org/latest/guides/west/index.html

manifest:
  
  remotes:
    - name: nxpmicro
      url-base: https://github.com/NXPmicro

  defaults:
    remote: nxpmicro

  projects:
    - name: mcux-sdk-examples
      revision: eeae217c66847c7380a5f02145cdf8844760574d
      path: examples
    - name: FreeRTOS-Kernel
      revision: MCUX_2.10.0
      path: rtos/freertos/freertos_kernel
    - name: mcux-sdk-middleware-sdmmc
      revision: MCUX_2.10.0
      path: middleware/sdmmc
    - name: mcux-sdk-middleware-multicore
      path: middleware/multicore
      revision: 50d7e6bd2e0501aad2944abe4eaf616fd465fb8e
    - name: rpmsg-lite
      path: middleware/multicore/rpmsg_lite
      url:  https://github.com/NXPmicro/rpmsg-lite
      revision: 3933134378690a9c04d533e26516b3388fe4acc3
    - name: erpc
      path: middleware/multicore/erpc
      url:  https://github.com/EmbeddedRPC/erpc
      revision: 1.8.1
    - name: mcux-soc-svd
      revision: 10bfbd06fff4e3387d366dcc11f8ab1c4fc4e303
      path: svd
    - name: fatfs
      path: middleware/fatfs
      revision: MCUX_2.10.0
    - name: mcux-sdk-middleware-eiq
      revision: MCUX_2.10.0
      path: middleware/eiq
    - name: mcux-sdk-middleware-deepviewrt
      revision: MCUX_2.10.0
      path: middleware/eiq/deepviewrt
    - name: mcux-sdk-middleware-glow
      revision: MCUX_2.10.0
      path: middleware/eiq/glow
    - name: mcux-sdk-middleware-tensorflow
      revision: MCUX_2.10.0
      path: middleware/eiq/tensorflow-lite
  self:
    path: core
